version: "3.9"

services:
  redis:
    container_name: todo-redis
    image: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: todo-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery_worker:
    build: .
    container_name: todo-celery-worker
    command: sh -c "celery -A core worker --loglevel=info"
    depends_on:
      - redis
      - backend
    volumes:
      - .:/app/

  celery_beat:
    build: .
    container_name: todo-celery-beat
    command: sh -c "celery -A core  beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - redis
      - backend
    volumes:
      - .:/app/

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      - '143:143'
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

volumes:
  smtp4dev-data:
