name: Django project test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ "3.9", "3.10" ]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Docker-Compose ${{ matrix.python-version }}
      with:
          python-version: ${{ matrix.python-version }}
      run: docker-compose up --build -d
    - name: Run tests
      run: docker exec backend sh -c "black . && flake8 && cd core/ && pytest ."
